name: oil-and-gas-club

services:
  course-backend:
    image: course-backend
    container_name: course-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_HTTP_PORTS=8080

  course-frontend:
    image: course-frontend-test
    container_name: course-frontend-test
    restart: unless-stopped
    ports:
      - "4008:4000"